extends: substitution
message: "Use '%s' instead of '%s'."
description: "Use typographically correct characters."
level: error
scope: text
swap:
  '\.\.\.': …
  '\([cC]\)': ©
  '\(TM\)': ™
  '\(tm\)': ™
  '\([rR]\)': ®
  '--': —
  '---': —
  '^\'': ''
  '\'$': '''
  '^"': ""
  '"$': """
