name: Run Tests

on:
  pull_request:
  workflow_dispatch:             # Allow manual triggering

jobs:
  test:
    uses: ./.github/workflows/tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
